### ISSUE TITLE
Initializing using template - No matching version found for @types/react@^18.2.0

### ISSUE THREAD

**Issue by jaskiratr** [fastly/remix-compute-js#5]
Hi,
I'm running the command to initialize the new Remix application with the provided template. It throws following error

```
npx @remix-run/dev create ./new-app-js --template https://github.com/fastly/remix-compute-js/tree/main/packages/remix-template

? TypeScript or JavaScript? JavaScript
? Do you want me to run `npm install`? Yes
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/react@^18.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jrandhawa/.npm/_logs/2023-03-08T05_53_11_755Z-debug-0.log
Error: Command failed: npm install
    at checkExecSyncError (node:child_process:841:11)
    at Object.execSync (node:child_process:912:15)
    at Object.createApp (/Users/jrandhawa/.npm/_npx/3e61c50fc2e5d4e6/node_modules/@remix-run/dev/dist/cli/create.js:205:19)
    at async Object.create (/Users/jrandhawa/.npm/_npx/3e61c50fc2e5d4e6/node_modules/@remix-run/dev/dist/cli/commands.js:102:3)
    at async Object.run (/Users/jrandhawa/.npm/_npx/3e61c50fc2e5d4e6/node_modules/@remix-run/dev/dist/cli/run.js:414:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 63630,
  stdout: null,
  stderr: null
}
```
I didn't find the `18.2.0` version for [@types/react](https://www.npmjs.com/package/@types/react?activeTab=versions)

So, I updated  `remix-compute-js/packages/remix-template/package.json` with
```
...
"@types/react": "^18.0.28",
"@types/react-dom": "^18.0.11",
...
```
And got the following output
```
npx @remix-run/dev create ./new-app-js --template ./remix-compute-js/packages/remix-template
? TypeScript or JavaScript? JavaScript
? Do you want me to run `npm install`? Yes
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@fastly/js-compute@1.4.1',
npm WARN EBADENGINE   required: { node: '16 - 19', npm: '^8' },
npm WARN EBADENGINE   current: { node: 'v16.17.0', npm: '9.6.0' }
npm WARN EBADENGINE }
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

added 1110 packages, and audited 1111 packages in 19s

246 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 That's it! `cd` into " **** /new-app-js" and check the README for development and deploy instructions!
```
Next, I tried running `npm run dev` and it failed to build the project
What am I doing wrong?

```
new-app-js % npm run dev  

> dev
> run-p "dev:*"


> dev:fastly
> fastly compute serve --watch


> dev:remix
> remix watch

Watching Remix app in development mode...
✓ Verifying package manifest
✓ Identifying package name
✓ Identifying toolchain
| Running [scripts.build]...💿 Built in 252ms
✗ Running [scripts.build]

INFO: Command output:
--------------------------------------------------------------------------------

> build
> npm run build:remix && npm run build:fastly


> build:remix
> remix build

Building Remix app in production mode...
Built in 213ms

> prebuild:fastly
> compute-js-static-publish --build-static --suppress-framework-warnings && webpack

Fastly Compute@Edge JavaScript Static Publisher
🚀 Building loader...
✔️ Public directory '/Users/jrandhawa/Documents/Code/remix on compute/new-app-js'.
✔️ Using static directories: ./public/build
✔️ Using exclude directories: ./node_modules
✔️ Applying 0 custom content type(s).
✔️ Using include directories: ./build, ./public
✔️ /build/index.js: "application/javascript"
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/build/index.js" to "./src/static-content/file0.txt".
✔️ /build/index.js.map: "application/json"
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/build/index.js.map" to "./src/static-content/file1.txt".
✔️ /public/build/_assets/index-4CHP7APY.css: "text/css" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/_assets/index-4CHP7APY.css" to "./src/static-content/file2.txt".
✔️ /public/build/_shared/chunk-7YF66SMO.js: "application/javascript" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/_shared/chunk-7YF66SMO.js" to "./src/static-content/file3.txt".
✔️ /public/build/_shared/chunk-SFIXD4SY.js: "application/javascript" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/_shared/chunk-SFIXD4SY.js" to "./src/static-content/file4.txt".
✔️ /public/build/entry.client-ZSOW72WA.js: "application/javascript" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/entry.client-ZSOW72WA.js" to "./src/static-content/file5.txt".
✔️ /public/build/manifest-B8DC76C4.js: "application/javascript" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/manifest-B8DC76C4.js" to "./src/static-content/file6.txt".
✔️ /public/build/root-PSZBA5KP.js: "application/javascript" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/root-PSZBA5KP.js" to "./src/static-content/file7.txt".
✔️ /public/build/routes/index-ZEXCD7P3.js: "application/javascript" [STATIC]
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/build/routes/index-ZEXCD7P3.js" to "./src/static-content/file8.txt".
✔️ /public/favicon.ico: "image/vnd.microsoft.icon"
✔️ Copied static binary file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/public/favicon.ico" to "./src/static-content/file9.bin".
✔️ /remix.config.js: "application/javascript"
✔️ Copied static string file "/Users/jrandhawa/Documents/Code/remix on compute/new-app-js/remix.config.js" to "./src/static-content/file10.txt".
✅  Wrote static file loader for 11 file(s).
✅  Wrote static file loader types file statics.d.ts.
asset index.js 779 KiB [compared for emit] [minimized] [big] (name: main) 1 related asset
orphan modules 361 KiB [orphan] 29 modules
runtime modules 1010 bytes 5 modules
modules by path ./node_modules/ 1.3 MiB
  javascript modules 1.29 MiB 157 modules
  json modules 12.7 KiB 6 modules
optional modules 280 bytes [optional]
  ./build/ lazy namespace object 160 bytes [optional] [built] [code generated]
  buffer (ignored) 15 bytes [optional] [built] [code generated]
  buffer (ignored) 15 bytes [optional] [built] [code generated]
  + 6 modules
./src/index.js + 4 modules 172 KiB [not cacheable] [built] [code generated]
./remix.config.js 474 bytes [built] [code generated]
util (ignored) 15 bytes [built] [code generated]
util (ignored) 15 bytes [built] [code generated]

WARNING in ./build/index.js 19:161-177
Critical dependency: the request of a dependency is an expression
 @ ./src/statics.js 7:0-49 12:163-174
 @ ./src/index.js 3:0-41 5:47-59

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  index.js (779 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (779 KiB)
      index.js

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.75.0 compiled with 5 warnings in 3993 ms

> build:fastly
> js-compute-runtime ./bin/index.js ./bin/main.wasm

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/jrandhawa/Documents/Code/remix'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at node:internal/main/check_syntax:32:20 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

SyntaxError: Invalid or unexpected token

--------------------------------------------------------------------------------

ERROR: error during execution process (see 'command output' above): exit status 1.

Here are some steps you can follow to debug the issue:

- Re-run the fastly command with the --verbose flag to see more information.
- Is the required language toolchain (node/npm, rust/cargo etc) installed correctly?
- Is the required version (if any) of the language toolchain installed/activated?
- Were the required dependencies (package.json, Cargo.toml etc) installed?
- Did the build script (see fastly.toml [scripts.build]) produce a ./bin/main.wasm binary file?
- Was there a configured [scripts.post_build] step that needs to be double-checked?

For more information on fastly.toml configuration settings, refer to https://developer.fastly.com/reference/compute/fastly-toml/
ERROR: "dev:fastly" exited with 1.
```

**Comment by harmony7** [comment]
I looks like the @types/react and @types/react-dom entries in package.json accidentally got bumped to 18.2, even though those don't exist.  This has been corrected.
